#!/usr/bin/env bash
#
# ontop-sqlite.sh — Materialize an RDF graph (Turtle) from a SQLite DB
#                   using the Ontop CLI.
#
# NOTE: SQLite is NOT officially supported by Ontop. It often works for
# simple mappings via the Xerial sqlite-jdbc driver, but complex SQL
# generated by Ontop (window functions, certain casts, string ops) may
# fail. If you hit a wall, convert your SQLite to DuckDB or PostgreSQL.
#
# Usage:
#   ./ontop-sqlite.sh -d data.db -m mapping.obda -o output.ttl [-t ont.ttl]
#
# Requires: bash, curl, unzip, java (>= 11)

set -euo pipefail

# ---------- configurable versions ----------
ONTOP_VERSION="${ONTOP_VERSION:-5.3.0}"
SQLITE_JDBC_VERSION="${SQLITE_JDBC_VERSION:-3.46.1.3}"

# ---------- paths ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ONTOP_HOME="${ONTOP_HOME:-${SCRIPT_DIR}/.ontop}"
ONTOP_BIN="${ONTOP_HOME}/ontop"
JDBC_DIR="${ONTOP_HOME}/jdbc"

# ---------- defaults ----------
DB_FILE=""
MAPPING_FILE=""
ONTOLOGY_FILE=""
OUTPUT_FILE="output.ttl"
FORMAT="turtle"

usage() {
  cat <<EOF
Usage: $0 -d <sqlite.db> -m <mapping> -o <output.ttl> [options]

Required:
  -d FILE    Path to the SQLite database file
  -m FILE    Ontop mapping file (.obda or R2RML .ttl)
  -o FILE    Output RDF file (default: output.ttl)

Optional:
  -t FILE    OWL ontology file (enables OWL reasoning on materialization)
  -f FMT     Output format: turtle|ntriples|rdfxml|nquads|trig|jsonld
             (default: turtle)
  -h         Show this help

Environment:
  ONTOP_VERSION         Ontop release to use (default: ${ONTOP_VERSION})
  SQLITE_JDBC_VERSION   Xerial sqlite-jdbc version (default: ${SQLITE_JDBC_VERSION})
  ONTOP_HOME            Where to install Ontop CLI (default: ./.ontop)
EOF
  exit "${1:-0}"
}

while getopts ":d:m:t:o:f:h" opt; do
  case "$opt" in
    d) DB_FILE="$OPTARG" ;;
    m) MAPPING_FILE="$OPTARG" ;;
    t) ONTOLOGY_FILE="$OPTARG" ;;
    o) OUTPUT_FILE="$OPTARG" ;;
    f) FORMAT="$OPTARG" ;;
    h) usage 0 ;;
    *) usage 1 ;;
  esac
done

[[ -z "$DB_FILE"      ]] && { echo "ERROR: -d (SQLite DB) is required"     >&2; usage 1; }
[[ -z "$MAPPING_FILE" ]] && { echo "ERROR: -m (mapping file) is required"  >&2; usage 1; }
[[ -f "$DB_FILE"      ]] || { echo "ERROR: DB file not found: $DB_FILE"    >&2; exit 1; }
[[ -f "$MAPPING_FILE" ]] || { echo "ERROR: mapping not found: $MAPPING_FILE" >&2; exit 1; }

# ---------- install Ontop CLI if missing ----------
if [[ ! -x "$ONTOP_BIN" ]]; then
  echo ">> Installing Ontop CLI ${ONTOP_VERSION} into ${ONTOP_HOME}"
  mkdir -p "$ONTOP_HOME"
  ZIP_URL="https://github.com/ontop/ontop/releases/download/ontop-${ONTOP_VERSION}/ontop-cli-${ONTOP_VERSION}.zip"
  TMP_ZIP="$(mktemp -t ontop-XXXXXX.zip)"
  trap 'rm -f "$TMP_ZIP"' EXIT
  curl -fsSL "$ZIP_URL" -o "$TMP_ZIP"
  unzip -q "$TMP_ZIP" -d "$ONTOP_HOME"
  chmod +x "$ONTOP_BIN"
fi

# ---------- fetch SQLite JDBC driver if missing ----------
mkdir -p "$JDBC_DIR"
if ! ls "$JDBC_DIR"/sqlite-jdbc-*.jar >/dev/null 2>&1; then
  echo ">> Downloading sqlite-jdbc ${SQLITE_JDBC_VERSION}"
  JAR_URL="https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/${SQLITE_JDBC_VERSION}/sqlite-jdbc-${SQLITE_JDBC_VERSION}.jar"
  curl -fsSL "$JAR_URL" -o "${JDBC_DIR}/sqlite-jdbc-${SQLITE_JDBC_VERSION}.jar"
fi

# ---------- generate a per-run properties file ----------
# Ontop expects an absolute path in the JDBC URL, and we use a dummy
# user/password because the CLI requires them even though SQLite ignores them.
DB_ABS="$(cd "$(dirname "$DB_FILE")" && pwd)/$(basename "$DB_FILE")"
PROPS_FILE="$(mktemp -t ontop-sqlite-XXXXXX.properties)"
trap 'rm -f "$PROPS_FILE"' EXIT

cat > "$PROPS_FILE" <<EOF
jdbc.url=jdbc:sqlite:${DB_ABS}
jdbc.driver=org.sqlite.JDBC
jdbc.user=sqlite
jdbc.password=sqlite
EOF

# ---------- run materialization ----------
echo ">> Materializing ${DB_FILE} -> ${OUTPUT_FILE} (${FORMAT})"
ONTOP_ARGS=(
  materialize
  -m "$MAPPING_FILE"
  -p "$PROPS_FILE"
  -f "$FORMAT"
  -o "$OUTPUT_FILE"
)
[[ -n "$ONTOLOGY_FILE" ]] && ONTOP_ARGS+=(-t "$ONTOLOGY_FILE")

"$ONTOP_BIN" "${ONTOP_ARGS[@]}"

echo ">> Done. Wrote ${OUTPUT_FILE}"
